### ISSUE TITLE
generic_config_updater.test_eth_interface::test_eth_interface_admin_change left Ethernet0 oper down on testbed

### ISSUE THREAD

**Issue by ZhaohuiS** [sonic-net/sonic-mgmt#11237]
**Description**

After test_eth_interface_admin_change, 7260 testbed became unhealthy since Ethernet0 is oper down. This case caused sanity check failure in next test case.

```
admin@str-7260cx3-acs-2:~$ show interface status
     Interface            Lanes    Speed    MTU    FEC         Alias            Vlan    Oper    Admin             Type    Asym PFC
--------------  ---------------  -------  -----  -----  ------------  --------------  ------  -------  ---------------  ----------
     Ethernet0            77,78      50G   9100     rs   Ethernet1/1           trunk    down       up  QSFP28 or later         off
     Ethernet2            79,80      50G   9100    N/A   Ethernet1/3           trunk      up       up  QSFP28 or later         off
     Ethernet4            65,66      50G   9100    N/A   Ethernet2/1           trunk      up       up  QSFP28 or later         off

```
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
Same issue was found on other testbeds. The issue was because the FEC mode of Ethernet0 is not recovered after the test running.

**Comment by isabelmsft** [comment]
This issue is not related to GCU. 

The issue can be reproduced directly using `sonic-db-cli` as follows: 

Before fec configuration change:
admin@SONIC:~$ show int status
     Interface            Lanes    Speed    MTU    FEC    Alias            Vlan    Oper    Admin             Type    Asym PFC
--------------  ---------------  -------  -----  -----  -------  --------------  ------  -------  ---------------  ----------
     Ethernet0              0,1      50G   9100     N/A    etp1a           trunk          up            up  QSFP28 or later         off

Change fec configuration via sonic-db-cli: 
admin@SONIC:~$ sonic-db-cli CONFIG_DB HSET "PORT|Ethernet0" "fec" "rs"

After fec configuration change:
admin@SONIC:~$ show int status
     Interface            Lanes    Speed    MTU    FEC    Alias            Vlan    Oper    Admin             Type    Asym PFC
--------------  ---------------  -------  -----  -----  -------  --------------  ------  -------  ---------------  ----------
     Ethernet0              0,1      50G   9100     rs    etp1a           trunk    down       up  QSFP28 or later         off

Oper status remains down. 

@prgeor , could you please help investigate the behavior above? Is this behavior expected, and why does it only happen on some SKU (e.g. Mellanox-SN3800) but not others (e.g. msn2700)?

**Comment by weiguo-nvidia** [comment]
Hi @prgeor , the issue still exist, could you help check, thanks!

**Comment by weiguo-nvidia** [comment]
Hi @ZhaohuiS , some questions need your help:

**Q1**
May I ask why do you think it is a test issue not product issue?


**Q2**
Test case `test_replace_fec` is skipped on `['Arista-7260CX3-D108C8', 'Arista-7260CX3-D108C10', 'Arista-7260CX3-Q64', 'Mellanox-SN3800-D112C8']` platform. As you said this is a test issue, why it is only skipped on these four platforms instead of all platform?

```
generic_config_updater/test_eth_interface.py::test_replace_fec:
  skip:
    reason: 'Skipping test on 7260/3800 platform due to bug of https://github.com/sonic-net/sonic-mgmt/issues/11237'
    conditions_logical_operator: "OR"
    conditions:
      - "hwsku in ['Arista-7260CX3-D108C8', 'Arista-7260CX3-D108C10', 'Arista-7260CX3-Q64', 'Mellanox-SN3800-D112C8'] and https://github.com/sonic-net/sonic-mgmt/issues/11237"
```


**Q3**
You mentioned `it only happen on some SKU (e.g. Mellanox-SN3800) but not others (e.g. msn2700)`, did it pass on msn2700? I encounter the same issue on msn2700 now.
