### ISSUE TITLE
[Bug]: `conditional_mark` only considers the longest match in the yaml file even when skipping.

### ISSUE THREAD

**Issue by arista-nwolfe** [sonic-net/sonic-mgmt#14698]
### Issue Description

As part of https://github.com/sonic-net/sonic-mgmt/pull/11968 there was a fix in the function `find_longest_matches` to now correctly find only the longest matching entry in `tests_mark_conditions.yaml`.

However, this bugfix now exposes the issue that multiple length'd `skip` conditions only result in the longest `skip` occurring and causing tests to be run on undesired SKUs.

### Results you see

E.G. looking specifically at `generic_config_updater/test_ecn_config_update.py::test_ecn_config_updates`

This test has 2 matching entries in `tests_mark_conditions.yaml`:
```
generic_config_updater:
  skip:
    reason: 'generic_config_updater is not a supported feature for T2'
    conditions:
      - "'t2' in topo_name"
```
```
generic_config_updater/test_ecn_config_update.py::test_ecn_config_updates:
  skip:
    reason: "This test is not run on this asic type, topology, or version currently"
    conditions_logical_operator: "OR"
    conditions:
      - "asic_type in ['cisco-8000']"
      - "topo_type in ['m0', 'mx']"
      - "release in ['202211']"
```

But now because of the fix we'll only use the latter rule because it's longer.
Meaning we no longer `skip` this test on T2 devices even though none of the tests in this `generic_config_updater` folder should run on T2.

In order to support this with the new "longest match wins" approach we'd need to replicate the `'t2' in topo_name` on every `generic_config_updater` rule.

### Results you expected to see

`generic_config_updater/test_ecn_config_update.py::test_ecn_config_updates` should be skipped on T2 topologies.

### Is it platform specific

generic
