### ISSUE TITLE
Bug: [topology] no expected routes in BGP session on ARISTA253

### ISSUE THREAD

**Issue by AntonHryshchuk** [sonic-net/sonic-mgmt#17794]
### Is it platform specific

generic

### Importance or Severity

Critical

### Description of the bug

ARISTA253 has only 1 route in the BGP session.
The root cause is that the defined IPv6 address for ARISTA253 can't be used, as this IP is already in use by a common configuration:
**nhipv6: FC0A::FF**

We should skip this IP in all related YML files:
topo_t0-isolated-d2u254.yml
topo_t0-isolated-d2u254s1.yml
topo_t0-isolated-d2u254s2.yml
topo_t0-isolated-d2u510.yml
topo_t1-isolated-d254u2.yml
topo_t1-isolated-d254u2s1.yml
topo_t1-isolated-d254u2s2.yml
topo_t1-isolated-d510u2.yml

### Steps to Reproduce

install on of related topologies and check numbers of routes on ARISTA253

### Actual Behavior and Expected Behavior

Actual configuration:
  _ARISTA253T1:
    properties:
    - common
    bgp:
      router-id: 0.12.0.255
      asn: 4200100000
      peers:
        4200000000:
          - fc00:a::3f9
    interfaces:
      Loopback0:
        **ipv6: fc00:c:c:ff::1/128**
      Ethernet1:
        ipv6: fc00:a::3fa/126
    bp_interface:
      **ipv6: fc0a::ff/64**_

Expected configuration:
```
  ARISTA252T1:
    properties:
    - common
    bgp:
      router-id: 0.12.0.254
      asn: 4200100000
      peers:
        4200000000:
          - fc00:a::3f5
    interfaces:
      Loopback0:
        ipv6: fc00:c:c:fe::1/128
      Ethernet1:
        ipv6: fc00:a::3f6/126
    bp_interface:
      ipv6: fc0a::fe/64

  ARISTA253T1:
    properties:
    - common
    bgp:
      router-id: 0.12.0.255
      asn: 4200100000
      peers:
        4200000000:
          - fc00:a::3f9
    interfaces:
      Loopback0:
        ipv6: fc00:c:c:100::1/128
      Ethernet1:
        ipv6: fc00:a::3fa/126
    bp_interface:
      ipv6: fc0a::100/64

  ARISTA254T1:
    properties:
    - common
    bgp:
      router-id: 0.12.1.0
      asn: 4200100000
      peers:
        4200000000:
          - fc00:a::3fd
    interfaces:
      Loopback0:
        ipv6: fc00:c:c:101::1/128
      Ethernet1:
        ipv6: fc00:a::3fe/126
    bp_interface:
      ipv6: fc0a::101/64
```

### Relevant log output

```shell

```

### Output of `show version`

```shell

```
