### ISSUE TITLE
Bug: [service port] incorrect configuration of service port in ALL topo files

### ISSUE THREAD

**Issue by AntonHryshchuk** [sonic-net/sonic-mgmt#18056]
### Is it platform specific

generic

### Importance or Severity

Critical

### Description of the bug

The configurations of service ports are not correct in topo files.

For example, the topo t0-isolated-d16u16s2:
```
  ARISTA01PT0:
    properties:
    - common
    bgp:
      asn: 65100
      peers:
        65100:
          - 10.0.2.0
          - fc00::401
    interfaces:
      Loopback0:
        ipv4: 100.1.1.1/32
        ipv6: 2064:100:0:101::/128
      Ethernet1:
        ipv4: 10.0.2.1/31
        ipv6: fc00::402/126
    bp_interface:
      ipv4: 10.10.247.2/24
      ipv6: fc0a::102/64
  ARISTA02PT0:
    properties:
    - common
    bgp:
      asn: 65100
      peers:
        65100:
          - 10.0.2.2
          - fc00::405
    interfaces:
      Loopback0:
        ipv4: 100.1.1.2/32
        ipv6: 2064:100:0:102::/128
      Ethernet1:
        ipv4: 10.0.2.3/31
        ipv6: fc00::406/126
    bp_interface:
      ipv4: 10.10.247.3/24
      ipv6: fc0a::103/64
```

With this configuration, the BGP session doesn't has a routes (see block "Actual Behavior and Expected Behavior").

**Need to change it to:**

  **ARISTA01PT0**:
    properties:
    - common
    bgp:
      **asn: 64601**
........
    bp_interface:
      ipv4: 10.10.**246.226**/24

  **ARISTA02PT0**:
    properties:
    - common
    bgp:
      **asn: 64602**
......
    bp_interface:
      ipv4: 10.10.**246.234**/24

### Steps to Reproduce

install t0-isolated-d16u16s2 topo on SN5640 testbed

### Actual Behavior and Expected Behavior

Current state in topo t0-isolated-d16u16s2:

_**ARISTA02PT0#show ip bgp summary**
BGP summary information for VRF default
Router identifier 100.1.1.2, local AS number 65100
Neighbor Status Codes: m - Under maintenance
  Description              Neighbor         V  AS           MsgRcvd   MsgSent  InQ OutQ  Up/Down State   PfxRcd PfxAcc
  65100                    10.0.2.2         4  65100           4110       892    0    0 00:44:22 Estab   6417   2
  **exabgp_v4                10.10.246.254    4  65100              0         0    0    0 00:44:23 Active**_ 

_**ARISTA02PT0#show running-config**
! Command: show running-config
..........
interface Ethernet5
   description backplane
   no switchport
   **ip address 10.10.247.3/24**
   ipv6 enable
   ipv6 address fc0a::103/64
   ipv6 nd ra disabled
........._

**ARISTA02PT0#ping 10.10.246.254**
PING 10.10.246.254 (10.10.246.254) 72(100) bytes of data.

--- 10.10.246.254 ping statistics ---
5 packets transmitted, 0 received, **100% packet loss**, time 40ms

_**root@SN5640:/home/admin# show ip bgp summary** 
...........
10.0.2.1       4  64601        222       3425     81052      0       0  00:10:54                **1  ARISTA01PT0**
10.0.2.3       4  64602        222       3425     81052      0       0  00:10:54                **1  ARISTA02PT0**_

**#############    The BGP sessions after changes    #############**:
root@SN5640:/home/admin# show ip bgp summary 
...........
10.0.2.1       4  64601       4604       4630     96471      0       0  01:10:50             **6368  ARISTA01PT0**
10.0.2.3       4  64602       4605       4633     96471      0       0  01:10:52             **6368  ARISTA02PT0**

**ARISTA02PT0#ping 10.10.246.254**
..........
--- 10.10.246.254 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.014/0.026/0.072/0.023 ms, ipg/ewma 0.039/0.048 ms

### Relevant log output

```shell

```

### Output of `show version`

```shell

```
